#!/usr/bin/env ruby

50.times do
  Thread.new do
    [
      lambda { `unicornleap 100 #{rand(100)}` },
      lambda { `trolleap 100 #{rand(100)}` }
    ].sample.call
  end

  sleep rand(3) / 10.0
end
